const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");

test("research shows full narrative and server pagination without truncating candidates", () => {
  const js = fs.readFileSync("price-watch.js", "utf8");
  assert.match(js, /data-chain-research-page/);
  assert.match(js, /data-research-history-page/);
  assert.match(js, /chainResearchPaging/);
  assert.match(js, /正在加载第.*页/);
  assert.match(js, /searchParams\.set\("researchPage"/);
  assert.match(js, /return true/);
  assert.match(js, /return false/);
  assert.match(js, /research\?\.selectedTotal/);
  assert.match(js, /事实依据与局限/);
  assert.match(js, /analysis\.identitySummary \|\| analysis\.summary/);
  assert.match(js, /待验证 \/ 失效条件/);
  assert.match(js, /展开完整 V4\.4 投研、叙事与风控/);
  assert.match(js, /注意力跃迁/);
  assert.match(js, /叙事发现/);
  assert.match(js, /映射关系/);
  assert.match(js, /龙头竞选/);
  assert.match(js, /下一触发条件/);
  assert.match(js, /研究保留/);
  assert.match(js, /龙头潜力/);
  assert.match(js, /大金狗潜力/);
  assert.match(js, /Firstness/);
  assert.match(js, /P0 \/ 母案例/);
  assert.match(js, /跨形态接力 \/ 行动窗口/);
  assert.match(js, /执行许可/);
  assert.match(js, /UNKNOWN 不等于安全/);
  assert.match(js, /推荐变更与撤回/);
  assert.match(js, /链上爆发 · 叙事待核验/);
  assert.match(js, /research\?\.provisionalTotal/);
  assert.match(js, /同链.*个同名合约/);
  assert.match(js, /龙一候选/);
  assert.match(js, /钱包结构/);
  assert.match(js, /同名分流/);
  assert.match(js, /群聊交叉验证/);
  assert.match(js, /news-triggered/);
  assert.match(js, /function binanceWalletTokenUrl\(row\)/);
  assert.match(js, /https:\/\/web3\.binance\.com\/en\/token/);
  assert.match(js, /const href = binanceWalletTokenUrl\(row\)/);
  assert.match(js, /在币安钱包打开当前链与 CA/);
  assert.match(js, /新闻触发 · CA明确/);
  assert.match(js, /已按 AI 结论、证据完整度、叙事强度与置信度从优到次排序/);
  assert.match(js, /openedResearch/);
  assert.doesNotMatch(js, /watching\.slice\(0, 12\)/);
  const css = fs.readFileSync("styles.css", "utf8");
  assert.match(css, /onchain-research-signal b,[\s\S]*white-space: normal/);
  assert.match(css, /\.onchain-research-selected\.is-provisional/);
  assert.match(css, /\.onchain-research-entry\.is-news-triggered/);
  assert.match(css, /\.onchain-framework-scores/);
  assert.match(css, /\.onchain-framework-permission\.is-block/);
});


test("price watch exposes chain ecosystem mode and API", () => {
  const html = fs.readFileSync("price-watch.html", "utf8");
  const js = fs.readFileSync("price-watch.js", "utf8");
  const css = fs.readFileSync("styles.css", "utf8");
  const server = fs.readFileSync("server.py", "utf8");

  assert.match(html, /data-watch-mode="chains"/);
  assert.match(js, /\/api\/chain-ecosystem/);
  assert.match(js, /renderChainEcosystem/);
  assert.match(js, /potentialProjects/);
  assert.match(js, /market\.candidates/);
  assert.match(js, /chain-discovery-row/);
  assert.match(js, /dailyResearch/);
  assert.match(js, /当前扫盘网络/);
  assert.match(js, /robinhood:\s*"Robinhood Chain"/);
  assert.match(js, /今日最值得研究/);
  assert.match(js, /research\?\.researchSourceLabel \|\| \"GMGN 战壕今日新币\"/);
  assert.match(js, /动态增量扫盘/);
  assert.match(js, /战壕 · 已开盘/);
  assert.match(js, /\/api\/onchain-trenches/);
  assert.match(js, /const direct = safeExternalUrl\(row\?\.binanceWalletUrl\)/);
  assert.match(js, /const href = binanceWalletTokenUrl\(row\) \|\| safeExternalUrl\(row\.tradeUrl\)/);
  assert.match(js, /币安钱包 ↗/);
  assert.match(server, /row\["binanceWalletUrl"\] = binance_wallet_contract_url/);
  assert.match(js, /正在直接连接 GMGN/);
  assert.match(js, /同一请求 90 秒合并复用/);
  assert.match(js, /已接入个人 Key/);
  assert.match(js, /CA · GMGN API/);
  assert.match(js, /GMGN API 正在限流冷却/);
  assert.match(js, /GMGN 战壕 · 已开盘/);
  assert.match(js, /row\.imageUrl/);
  assert.match(js, /Top10/);
  assert.match(js, /开发者持仓|creatorHoldingPercent/);
  assert.match(js, /sniperHoldingPercent/);
  assert.match(js, /bundlerHoldingPercent/);
  assert.match(js, /smartMoneyHolders/);
  assert.match(js, /GMGN AI 叙事/);
  assert.match(js, /悬停不发起新请求/);
  assert.match(js, /打开原 X/);
  assert.match(js, /在 GMGN 搜索/);
  assert.doesNotMatch(js, /\/api\/onchain-trenches\/ai/);
  assert.doesNotMatch(js, /scheduleOnchainTrenchAiPoll/);
  assert.match(js, /data-trench-network/);
  assert.doesNotMatch(js, /data-trench-source/);
  assert.match(js, /data-trench-page/);
  assert.match(js, /data-trench-refresh/);
  assert.match(js, /data-chain-research-day/);
  assert.match(js, /researchDay/);
  assert.match(js, /页面只保留需要你复核的候选/);
  assert.match(js, /需要你看的候选/);
  assert.doesNotMatch(js, /已过滤噪音/);
  assert.match(js, /公链生态图谱/);
  assert.match(js, /历史龙头复盘/);
  assert.match(js, /系统状态/);
  assert.match(js, /data-chain-submode/);
  assert.match(js, /chainView/);
  assert.match(js, /data-chain-select/);
  assert.match(js, /data-chain-project-form/);
  assert.doesNotMatch(js, /token_trading:\s*"发币 \/ 交易"/);
  assert.match(css, /\.price-watch-grid\.is-chains/);
  assert.match(css, /\.chain-ecosystem-console/);
  assert.match(css, /\.chain-ecosystem-sidebar/);
  assert.match(css, /\.chain-market-card/);
  assert.match(css, /\.chain-ranking-row/);
  assert.match(css, /\.chain-potential-pool/);
  assert.match(css, /\.onchain-research-board/);
  assert.match(css, /\.onchain-research-networks/);
  assert.match(css, /\.chain-research-subnav/);
  assert.match(css, /\.chain-research-view/);
  assert.match(css, /\.onchain-trenches-board/);
  assert.match(css, /\.onchain-trench-row/);
  assert.match(css, /\.onchain-trench-mainline/);
  assert.match(css, /\.onchain-trench-chipline/);
  assert.match(css, /\.onchain-trench-hover-card/);
  assert.match(css, /\.onchain-trench-social-tool/);
  assert.match(css, /\.onchain-research-candidate/);
  assert.match(css, /\.onchain-research-cases/);
  assert.match(css, /\.price-watch-add-form\[hidden\]/);
  assert.match(css, /@media \(max-width: 980px\)[\s\S]*\.chain-ecosystem-console/);
});

test("NFT rankings show OpenSea floor price instead of token liquidity", () => {
  const js = fs.readFileSync("price-watch.js", "utf8");
  assert.match(js, /marketKey === "nft"/);
  assert.match(js, /metrics\.floorPriceNative/);
  assert.match(js, /地板价/);
  assert.match(js, /OpenSea · NFT/);
});

test("News Trade renders MEME opportunity evidence and a guarded per-candidate buy action", () => {
  const js = fs.readFileSync("price-watch.js", "utf8");
  assert.match(js, /memeOpportunity/);
  assert.match(js, /data-news-trade-prepare/);
  assert.match(js, /\/api\/news-trade\/prepare/);
  assert.match(js, /class="news-trade-candidate-buy /);
  assert.match(js, /data-news-trade-contract/);
  assert.match(js, /manualIntent: true/);
  assert.match(js, /系统不主动推荐；仍可按你的手动意图买入/);
  assert.doesNotMatch(js, /eventId\s*&&\s*context\.executionEligible/);
});

test("News Trade groups ranked candidates into paginated topic cards", () => {
  const js = fs.readFileSync("price-watch.js", "utf8");
  const css = fs.readFileSync("styles.css", "utf8");
  assert.match(js, /NEWS_TRADE_PAGE_SIZE\s*=\s*10/);
  assert.match(js, /memeCandidates/);
  assert.match(js, /TOP1 主标/);
  assert.match(js, /data-news-trade-page/);
  assert.match(css, /\.news-trade-candidate\.is-primary/);
  assert.match(css, /\.news-trade-candidate\.is-backup/);
  assert.match(css, /\.news-trade-pagination/);
  assert.match(css, /\.news-trade-dual-score/);
  assert.match(css, /\.news-trade-intel-grid/);
  assert.match(js, /eventHeatScore/);
  assert.match(js, /onchainTradeScore/);
  assert.match(js, /associationLabel/);
});

test("News Trade exposes timing and narrative score labels on every topic card", () => {
  const js = fs.readFileSync("price-watch.js", "utf8");
  const css = fs.readFileSync("styles.css", "utf8");
  assert.match(js, /0–6h 先手理解/);
  assert.match(js, /6–24h 预发酵/);
  assert.match(js, /新奇猎奇/);
  assert.match(js, /争议性/);
  assert.match(js, /讨论度/);
  assert.match(js, /传奇性/);
  assert.match(js, /名字寓意/);
  assert.match(js, /newsTradeScoreTagsTemplate/);
  assert.match(css, /\.news-trade-score-tags/);
  assert.match(css, /\.news-trade-phase\.is-fermented/);
});

test("News Trade supports active topic discovery with a confirm-before-add preview", () => {
  const js = fs.readFileSync("price-watch.js", "utf8");
  const css = fs.readFileSync("styles.css", "utf8");
  assert.match(js, /data-news-trade-search/);
  assert.match(js, /\/api\/news-trade\/search/);
  assert.match(js, /加入主题监控/);
  assert.match(js, /previewId/);
  assert.match(css, /\.news-trade-search-panel/);
  assert.match(css, /\.news-trade-search-preview/);
});

test("News Trade connects OKX and Binance Wallet without exposing private key material", () => {
  const page = fs.readFileSync("price-watch.js", "utf8");
  const wallets = fs.readFileSync("wallets.js", "utf8");
  const css = fs.readFileSync("styles.css", "utf8");
  assert.match(page, /const wallets = window\.XingyunWallets/);
  assert.match(page, /walletProvider: adapter\.authorizationProvider \|\| "injected"/);
  assert.match(wallets, /window\.okxwallet/);
  assert.match(wallets, /window\.binancew3w/);
  assert.match(wallets, /eth_requestAccounts/);
  assert.match(wallets, /accountsChanged/);
  assert.match(wallets, /wallet_switchEthereumChain/);
  assert.doesNotMatch(`${page}\n${wallets}`, /eth_privateKey|助记词.*输入/);
  assert.match(css, /\.news-trade-wallet/);
});
